# Generated by Django 6.1 on 2026-09-01 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('publie', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: A4, S, G1, F2', max_length=10, unique=True)),
                ('nom', models.CharField(help_text='Ex: Lettres et Philosophie', max_length=150)),
                ('cycle', models.CharField(choices=[('general', 'Enseignement Général'), ('technique', 'Enseignement Technique')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('classe_precedente', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('contactee', 'Contactée'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='nouvelle', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('serie_souhaitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='core.serie')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
