# Generated by Django 6.1 on 2026-09-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('club', 'Club'), ('sport', 'Sport'), ('culture', 'Culture'), ('evenement', 'Événement')], default='club', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vie-etudiante/')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Activité (vie étudiante)',
                'verbose_name_plural': 'Activités (vie étudiante)',
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
