# Generated by Django 6.1 on 2026-09-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(upload_to='galerie/')),
                ('legende', models.CharField(blank=True, max_length=250)),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Photo (galerie)',
                'verbose_name_plural': 'Photos (galerie)',
                'ordering': ['ordre', '-id'],
            },
        ),
    ]
